### ISSUE TITLE
Is /ipfs/ a required prefix for ipfsPaths?

### ISSUE THREAD

**Issue by JonKrone** [ipfs-shipyard/is-ipfs#14]
In some other places such as the http/cli interfaces we consider the `/ipfs/` prefix to be optional. Does that extend here as well? i.e: should the following paths be considered valid under `isIPFS.ipfsPath`?

- `QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V`
- `QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V/link/to/somewhere`

I'm not sure if this library is intentionally a little more strict or if there is another use case I'm missing. Thanks!

**Comment by lidel** [comment]
Hi, yes, we are intentionally strict here. 
Valid IPFS path is a NURI (nestable uri a.k.a. unix path) starting with `/ipfs/` prefix. 
If you have CIDs in raw form (without `/ipfs/` prefix), you need to proper prefix before you pass it to validation method.
