### ISSUE TITLE
ipfs peer support

### ISSUE THREAD

**Issue by MichaelMure** [ipfs-shipyard/is-ipfs#15]
It would be nice to support ipfs peer ID as well.

I'm not sure but `is-ipfs.multihash()` might works for this purpose, but at least for the semantic, a specific function would be nice.

**Comment by lidel** [comment]
For now multihash one will work for most uses in the wild.
In the future, after https://github.com/ipfs/go-ipfs/issues/5287 is solved we will add a dedicated method for peerids.

**Comment by achingbrain** [comment]
Closing due to staleness.
