### ISSUE TITLE
isIPFS.cid('11') returns true

### ISSUE THREAD

**Issue by ingria** [ipfs-shipyard/is-ipfs#50]
I'm not sure, but as far as I understand, '11' is not a valid CID.

Steps to reproduce:

```javascript
import isIPFS from 'is-ipfs'
console.log(isIPFS.cid('11'))

>>> true
```

**Comment by suhailtajshaik** [comment]
It working as expected @ingria 

`const isIPFS = require('is-ipfs');
console.log(isIPFS.cid('11'))

>>> false
`
