### ISSUE TITLE
Support for CommonJS

### ISSUE THREAD

**Issue by vikiival** [ipfs-shipyard/is-ipfs#61]
## Problem

Hello I want to use is-ipfs package in https://github.com/subsquid project.
However this package does not support CommonJS.

## Solution

Ideally export CommonJS files as .cjs and ESM as .mjs
Not sure if aegir (esmbuild) can support that.

## Blocker

The support could be blocked by https://github.com/multiformats/js-multiformats/issues/220

**Comment by achingbrain** [comment]
This module is [ESM only](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) - you can use [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) to load it from CJS.
