### ISSUE TITLE
bug: is-ipfs types not recognized in output

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/is-ipfs#88]
see https://github.com/ipfs/ipfs-companion/pull/1256/files

**Comment by achingbrain** [comment]
This is working fine in [other TS projects](https://github.com/ipfs/helia/blob/6c88ee1530861357d23ea49d20aac3c1b5aa0bd9/packages/ipns/src/utils/dns.ts#L2), please re-open if you're still having problems.
